plugins {
    id 'java'
    id 'application'
}

group 'com.gestiontaches'
version '1.0-SNAPSHOT'

sourceCompatibility = '17'
targetCompatibility = '17'

repositories {
    mavenCentral()
}

application {
    mainClass = 'com.gestiontaches.Application'
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}
